Update fail2ban-proxmox-firewall

diff --git a/PROXMOX/usr/local/bin/fail2ban-proxmox-firewall b/PROXMOX/usr/local/bin/fail2ban-proxmox-firewall
--- a/PROXMOX/usr/local/bin/fail2ban-proxmox-firewall
+++ b/PROXMOX/usr/local/bin/fail2ban-proxmox-firewall
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-PVE_NODE_FW="/etc/pve/firewall/100.fw"
+PVE_CLUSTER_FW="/etc/pve/firewall/cluster.fw"
 
 if [ "$#" -ne 2 ]; then
     echo "Usage: $0 {add|remove} <IP>"
@@ -10,19 +10,19 @@ fi
 ACTION=$1
 IP=$2
 
-# Ensure node firewall file exists
-if [ ! -f "$PVE_NODE_FW" ]; then
-    touch "$PVE_NODE_FW"
+# Ensure cluster firewall file exists
+if [ ! -f "$PVE_CLUSTER_FW" ]; then
+    touch "$PVE_CLUSTER_FW"
 fi
 
 if [ "$ACTION" == "add" ]; then
-    # Add rule to node firewall if not already present
-    if ! grep -q "IN DROP -source $IP" "$PVE_NODE_FW"; then
-        echo "IN DROP -source $IP -log nolog # Fail2Ban Blocked" >> "$PVE_NODE_FW"
+    # Add rule to cluster firewall if not already present
+    if ! grep -q "IN DROP -source $IP" "$PVE_CLUSTER_FW"; then
+        echo "IN DROP -source $IP -log nolog # Fail2Ban Blocked" >> "$PVE_CLUSTER_FW"
     fi
 elif [ "$ACTION" == "remove" ]; then
-    # Remove rule from node firewall
-    sed -i "/IN DROP -source $IP -log nolog # Fail2Ban Blocked/d" "$PVE_NODE_FW"
+    # Remove rule from cluster firewall
+    sed -i "/IN DROP -source $IP -log nolog # Fail2Ban Blocked/d" "$PVE_CLUSTER_FW"
 else
     echo "Invalid action: $ACTION (use 'add' or 'remove')"
     exit 1
